---
title: "Aggregate Results"
output: html_notebook
---

# Read Data
```{r}

load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/US/us_list_results.RData")
load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/UK/uk_list_results.RData")
load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/GER/ger_list_results.RData")

```

# Check Results
### Results US
```{r}
# us_list_results %>% map(summary)
```

### Results UK
```{r}
# uk_list_results %>% map(summary)
```

### Results GER
```{r}
# ger_list_results %>% map(summary)
```


# Create Single List Object
```{r}

covid_results <- list(us_list_results, uk_list_results, ger_list_results)
names(covid_results) <- c('US', 'UK', 'GER')

save(covid_results, file="/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Delivery/covid_results.RData")

```

# Extract effect sizes and SE
```{r}

# define extractor function
extractor <- function(x){
   if(ncol(x)==5){
      subset <- x[,c(1,3,5)]
   }else{
      subset <- x[,c(1,2,4)]
   }
}

renamer <- function(x){
   names(x) <- c('coef', 'se', 'p')
   x <- x %>% rownames_to_column(var = "predictor")
   return(x)
}

corstars <- function(x){
   x <- x %>% 
      mutate(stars = ifelse(p < 0.05, '*', '')) %>%
      mutate(stars = ifelse(p < 0.01, '**', stars)) %>%
      mutate(stars = ifelse(p < 0.001, '***', stars))
   return(x)
}




dataframer <- function(x){
   
   results_names <- list('cox_onset_prev', 'cox_onset_prev_ctrl', 
     'lm_slope_prev', 'lm_slope_prev_ctrl', 
     'cox_cpt_socdist', 'cox_cpt_socdist_ctrl', 
     'lm_meandiff_socdist', 'lm_meandiff_socdist_ctrl',
     'cox_cpt_socdist_2', 'cox_cpt_socdist_ctrl_2',
     'lm_meandiff_socdist_2', 'lm_meandiff_socdist_ctrl_2')
   
   x <- x %>% map(summary) %>%
      map(function(x) x$coefficients) %>%
      map(extractor) %>%
      map(as.data.frame) %>%
      map(renamer)
      
   
   names(x) <- results_names
   
   x <- x %>% map(corstars) %>%
      map_if(is.numeric, round, digits=5)

   return(x)
   
}
```


```{r}

covid_results_df <- covid_results %>% map(dataframer)

covid_results_df
```

# Save Final List of Dataframes

```{r}
save(covid_results_df, file="/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Delivery/covid_results_df.RData")

```
