---
title: "Aggregate Results"
output: html_notebook
---

# Read Data
```{r}

load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/US/us_agg.RData")
load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/US/us_agg_fixed_window.RData")
load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/GER/ger_agg.RData")
load("/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Data/GER/ger_agg_fixed_window.RData")

```


```{r}

combiner <- function(x){
   
   dv <- rep(c('cox_prev_onset', 
                   'lm_prev_slope',
                   'cox_socdist_cpt', 
                   'lm_socdist_mean'), 
                 each=25)
   x <- x %>% bind_rows()
   x <- cbind(dv, x)
   return(x)
}


```


### US onset-base slopes
```{r}
us_all <- us_agg %>% combiner()
us_all
```

### US fixed window slopes
```{r}
us_all_fw <- us_agg_fixed_window %>% combiner()
us_all_fw
```

### GER onset-base slopes
```{r}
ger_all <- ger_agg %>% combiner()
ger_all
```

### GER onset-base slopes
```{r}
ger_all_fw <- ger_agg_fixed_window %>% combiner()
ger_all_fw
```

```{r}
list_all_results <- list(us_all, us_all_fw,
                         ger_all, ger_all_fw)
names(list_all_results) <- c('us_all', 'us_all_fw', 
                             'ger_all', 'ger_all_fw')
```


```{r}

df_all_results <- cbind(us_all %>% select(dv, trait, model,stars),
                        us_all_fw %>% select(stars), 
                        ger_all %>% select(stars),
                        ger_all_fw %>% select(stars)) 
names(df_all_results) <- c("dv", "trait", "model", 
                           "sig_us", "sig_us_fw", 
                           "sig_ger", "sig_ger_fw")
df_all_results
```


# Save Final List of Dataframes

```{r}
save(df_all_results, file="/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Delivery/covid_results_df.RData")

save(list_all_results, file="/Users/hp2500/Google Drive/STUDY/Columbia/Research/Corona/Delivery/covid_results_list.RData")

```
